import re
from typing import Dict, List, Set, Tuple, Optional, Any
from ..ir.tac import (
    TACProgram, TACFunction, TACInstruction, Opcode,
    Operand, Temp, Var, Constant, Label
)


class CEmitter:
    """Translates TACProgram into standard C source code with value semantics.
    
    All arrays and strings are wrapped in single-field C structs to guarantee
    true copy semantics for assignments, function arguments, and return values.
    """

    def __init__(self):
        self.array_types: Dict[str, str] = {}  # type_spec_str -> c_typedef_name
        self.struct_names: Set[str] = set()

    def emit(self, program: TACProgram) -> str:
        """Emit complete C99 source string for the given TACProgram."""
        self.array_types.clear()
        self.struct_names = set(program.structs.keys())

        # Collect all array/string types from structs, globals, functions
        self._collect_types(program)

        sections: List[str] = []

        # 1. Standard Prelude
        sections.append(self._emit_prelude())

        # 2. Array / String Typedef Wrappers
        array_typedefs = self._emit_array_typedefs()
        if array_typedefs:
            sections.append(array_typedefs)

        # 3. User Struct Definitions
        struct_defs = self._emit_struct_definitions(program.structs)
        if struct_defs:
            sections.append(struct_defs)

        # 4. Global Variable Declarations
        global_decls = self._emit_global_variables(program.global_vars)
        if global_decls:
            sections.append(global_decls)

        # 5. Function Prototypes (forward declarations)
        prototypes = self._emit_prototypes(program.functions)
        if prototypes:
            sections.append(prototypes)

        # 6. Function Implementations
        for func in program.functions:
            sections.append(self._emit_function(func))

        return "\n\n".join(sections) + "\n"

    def _emit_prelude(self) -> str:
        return (
            "// Generated by MiniC Compiler Optimizer\n"
            "#include <stdio.h>\n"
            "#include <stdlib.h>\n"
            "#include <string.h>\n"
            "#include <stdbool.h>"
        )

    def _collect_types(self, program: TACProgram) -> None:
        # Collect from structs
        for s_name, fields in program.structs.items():
            for f_name, f_type in fields.items():
                self._register_type(f_type)

        # Collect from globals
        for g_name, g_type, _ in program.global_vars:
            self._register_type(g_type)

        # Collect from functions
        for func in program.functions:
            self._register_type(func.return_type)
            for p_name, p_type in func.params:
                self._register_type(p_type)
            for var_name, var_type in func.local_types.items():
                self._register_type(var_type)

    def _register_type(self, type_str: str) -> None:
        if "[" in type_str:
            self._get_c_type(type_str)

    def _get_c_type(self, type_str: str) -> str:
        """Convert a MiniC type string (e.g. 'int[3][3]', 'struct Point', 'char[6]') to a valid C type."""
        type_str = type_str.strip()
        if not type_str or type_str == "void":
            return "void"

        # Check for 2D array: base[dim1][dim2]
        match_2d = re.match(r"^(.+)\[(\d+)\]\[(\d+)\]$", type_str)
        if match_2d:
            base, d1, d2 = match_2d.group(1).strip(), match_2d.group(2), match_2d.group(3)
            clean_base = self._clean_identifier(base)
            c_typedef_name = f"arr_{clean_base}_{d1}_{d2}"
            self.array_types[type_str] = c_typedef_name
            return c_typedef_name

        # Check for 1D array / string: base[dim1]
        match_1d = re.match(r"^(.+)\[(\d+)\]$", type_str)
        if match_1d:
            base, d1 = match_1d.group(1).strip(), match_1d.group(2)
            clean_base = self._clean_identifier(base)
            if base == "char":
                c_typedef_name = f"str_{d1}"
            else:
                c_typedef_name = f"arr_{clean_base}_{d1}"
            self.array_types[type_str] = c_typedef_name
            return c_typedef_name

        # Struct type: 'struct Point' or 'Point'
        if type_str.startswith("struct "):
            s_name = type_str[7:].strip()
            return s_name
        if type_str in self.struct_names:
            return type_str

        # Primitives
        return type_str

    def _clean_identifier(self, type_name: str) -> str:
        if type_name.startswith("struct "):
            type_name = type_name[7:].strip()
        return re.sub(r"[^a-zA-Z0-9_]", "_", type_name)

    def _emit_array_typedefs(self) -> str:
        lines: List[str] = []
        if not self.array_types:
            return ""

        lines.append("// --- Value-Semantics Array/String Wrapper Structs ---")
        for type_str, typedef_name in self.array_types.items():
            # 2D array
            match_2d = re.match(r"^(.+)\[(\d+)\]\[(\d+)\]$", type_str)
            if match_2d:
                base, d1, d2 = match_2d.group(1).strip(), match_2d.group(2), match_2d.group(3)
                c_base = self._get_c_type(base)
                lines.append(f"typedef struct {{ {c_base} data[{d1}][{d2}]; }} {typedef_name};")
                continue

            # 1D array / string
            match_1d = re.match(r"^(.+)\[(\d+)\]$", type_str)
            if match_1d:
                base, d1 = match_1d.group(1).strip(), match_1d.group(2)
                c_base = self._get_c_type(base)
                lines.append(f"typedef struct {{ {c_base} data[{d1}]; }} {typedef_name};")
                continue

        return "\n".join(lines)

    def _emit_struct_definitions(self, structs: Dict[str, Dict[str, str]]) -> str:
        if not structs:
            return ""

        lines: List[str] = ["// --- User Struct Definitions ---"]
        for s_name, fields in structs.items():
            lines.append(f"typedef struct {s_name} {{")
            for f_name, f_type in fields.items():
                c_type = self._get_c_type(f_type)
                lines.append(f"    {c_type} {f_name};")
            lines.append(f"}} {s_name};\n")

        return "\n".join(lines).strip()

    def _emit_global_variables(self, globals_list: List[Tuple[str, str, Optional[Any]]]) -> str:
        if not globals_list:
            return ""

        lines: List[str] = ["// --- Global Variables ---"]
        for g_name, g_type, init_val in globals_list:
            c_type = self._get_c_type(g_type)
            if init_val is not None:
                if isinstance(init_val, str):
                    lines.append(f"{c_type} {g_name} = ({c_type}){{ .data = {self._format_string_literal(init_val)} }};")
                else:
                    lines.append(f"{c_type} {g_name} = {init_val};")
            else:
                lines.append(f"{c_type} {g_name};")

        return "\n".join(lines)

    def _emit_prototypes(self, functions: List[TACFunction]) -> str:
        lines: List[str] = ["// --- Function Prototypes ---"]
        for func in functions:
            ret_type = self._get_c_type(func.return_type)
            if not func.params:
                params_str = "void" if func.name == "main" else ""
            else:
                params_str = ", ".join(f"{self._get_c_type(p_type)} {p_name}" for p_name, p_type in func.params)
            lines.append(f"{ret_type} {func.name}({params_str});")
        return "\n".join(lines)

    def _emit_function(self, func: TACFunction) -> str:
        lines: List[str] = []
        ret_type = self._get_c_type(func.return_type)
        if not func.params:
            params_str = "void" if func.name == "main" else ""
        else:
            params_str = ", ".join(f"{self._get_c_type(p_type)} {p_name}" for p_name, p_type in func.params)

        lines.append(f"{ret_type} {func.name}({params_str}) {{")

        # Collect local variables and temporaries
        param_names = {p[0] for p in func.params}
        local_vars: Dict[str, str] = {}  # name -> c_type

        for name, type_str in func.local_types.items():
            if name not in param_names:
                local_vars[name] = self._get_c_type(type_str)

        # Also inspect any undeclared temporaries or operands in instructions
        for inst in func.instructions:
            for op in (inst.dst, inst.src1, inst.src2, inst.src3):
                if isinstance(op, Temp) and str(op) not in local_vars and str(op) not in param_names:
                    local_vars[str(op)] = self._get_c_type(op.type_str)
                elif isinstance(op, Var) and op.name not in local_vars and op.name not in param_names:
                    local_vars[op.name] = self._get_c_type(op.type_str)

        # Emit declarations (zero-initialized for safety)
        if local_vars:
            lines.append("    // Local declarations")
            for var_name, c_type in sorted(local_vars.items()):
                lines.append(f"    {c_type} {var_name} = ({c_type}){{0}};")
            lines.append("")

        # Emit instruction body
        pending_params: List[str] = []
        for inst in func.instructions:
            c_line = self._emit_instruction(inst, pending_params, local_vars)
            if c_line:
                lines.append(f"    {c_line}")

        lines.append("}")
        return "\n".join(lines)

    def _emit_instruction(self, inst: TACInstruction, pending_params: List[str], local_vars: Dict[str, str]) -> str:
        op = inst.opcode

        if op == Opcode.LABEL:
            return f"{inst.dst}: ;"

        elif op == Opcode.JUMP:
            return f"goto {inst.dst};"

        elif op == Opcode.JUMP_IF_TRUE:
            src = self._format_operand(inst.src1)
            return f"if ({src}) goto {inst.dst};"

        elif op == Opcode.JUMP_IF_FALSE:
            src = self._format_operand(inst.src1)
            return f"if (!({src})) goto {inst.dst};"

        elif op == Opcode.ASSIGN:
            dst_str = self._format_operand(inst.dst)
            # Check if source is a string constant
            if isinstance(inst.src1, Constant) and inst.src1.type_str == "string":
                dst_type = local_vars.get(dst_str, f"str_{len(inst.src1.value) + 1}")
                str_lit = self._format_string_literal(inst.src1.value)
                return f"{dst_str} = ({dst_type}){{ .data = {str_lit} }};"
            src_str = self._format_operand(inst.src1)
            return f"{dst_str} = {src_str};"

        elif op in (
            Opcode.ADD, Opcode.SUB, Opcode.MUL, Opcode.DIV, Opcode.MOD,
            Opcode.EQ, Opcode.NE, Opcode.LT, Opcode.LE, Opcode.GT, Opcode.GE,
            Opcode.LOGIC_AND, Opcode.LOGIC_OR
        ):
            symbols = {
                Opcode.ADD: "+", Opcode.SUB: "-", Opcode.MUL: "*", Opcode.DIV: "/", Opcode.MOD: "%",
                Opcode.EQ: "==", Opcode.NE: "!=", Opcode.LT: "<", Opcode.LE: "<=", Opcode.GT: ">", Opcode.GE: ">=",
                Opcode.LOGIC_AND: "&&", Opcode.LOGIC_OR: "||"
            }
            dst = self._format_operand(inst.dst)
            s1 = self._format_operand(inst.src1)
            s2 = self._format_operand(inst.src2)
            sym = symbols[op]
            return f"{dst} = {s1} {sym} {s2};"

        elif op == Opcode.NEG:
            dst = self._format_operand(inst.dst)
            s1 = self._format_operand(inst.src1)
            return f"{dst} = -({s1});"

        elif op == Opcode.LOGIC_NOT:
            dst = self._format_operand(inst.dst)
            s1 = self._format_operand(inst.src1)
            return f"{dst} = !({s1});"

        elif op == Opcode.PARAM:
            pending_params.append(self._format_operand(inst.src1))
            return ""

        elif op == Opcode.CALL:
            func_name = str(inst.src1)
            args_str = ", ".join(pending_params)
            pending_params.clear()
            if inst.dst:
                dst = self._format_operand(inst.dst)
                return f"{dst} = {func_name}({args_str});"
            else:
                return f"{func_name}({args_str});"

        elif op == Opcode.RETURN:
            if inst.src1 is not None:
                src = self._format_operand(inst.src1)
                return f"return {src};"
            return "return;"

        elif op == Opcode.LOAD_ARR_1D:
            dst = self._format_operand(inst.dst)
            arr = self._format_operand(inst.src1)
            idx = self._format_operand(inst.src2)
            return f"{dst} = {arr}.data[{idx}];"

        elif op == Opcode.STORE_ARR_1D:
            arr = self._format_operand(inst.dst)
            idx = self._format_operand(inst.src1)
            val = self._format_operand(inst.src2)
            return f"{arr}.data[{idx}] = {val};"

        elif op == Opcode.LOAD_ARR_2D:
            dst = self._format_operand(inst.dst)
            arr = self._format_operand(inst.src1)
            idx1 = self._format_operand(inst.src2)
            idx2 = self._format_operand(inst.src3)
            return f"{dst} = {arr}.data[{idx1}][{idx2}];"

        elif op == Opcode.STORE_ARR_2D:
            arr = self._format_operand(inst.dst)
            idx1 = self._format_operand(inst.src1)
            idx2 = self._format_operand(inst.src2)
            val = self._format_operand(inst.src3)
            return f"{arr}.data[{idx1}][{idx2}] = {val};"

        elif op == Opcode.GET_FIELD:
            dst = self._format_operand(inst.dst)
            struct_var = self._format_operand(inst.src1)
            field = str(inst.src2)
            return f"{dst} = {struct_var}.{field};"

        elif op == Opcode.SET_FIELD:
            struct_var = self._format_operand(inst.dst)
            field = str(inst.src1)
            val = self._format_operand(inst.src2)
            return f"{struct_var}.{field} = {val};"

        elif op == Opcode.ALLOC_LOCAL:
            # Handled in local declarations prologue
            return ""

        elif op == Opcode.COMMENT:
            return f"// {inst.annotation}"

        return ""

    def _format_operand(self, op: Any) -> str:
        if op is None:
            return ""
        if isinstance(op, Constant):
            if op.type_str == "string":
                return self._format_string_literal(op.value)
            elif op.type_str == "char":
                return self._format_char_literal(op.value)
            elif op.type_str == "float":
                f_val = float(op.value)
                return f"{f_val}f"
            return str(op.value)
        elif isinstance(op, (Temp, Var, Label)):
            return str(op)
        return str(op)

    def _format_string_literal(self, s: str) -> str:
        escaped = (
            s.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\n", "\\n")
            .replace("\t", "\\t")
            .replace("\r", "\\r")
            .replace("\0", "\\0")
        )
        return f'"{escaped}"'

    def _format_char_literal(self, c: str) -> str:
        escaped = (
            c.replace("\\", "\\\\")
            .replace("'", "\\'")
            .replace("\n", "\\n")
            .replace("\t", "\\t")
            .replace("\r", "\\r")
            .replace("\0", "\\0")
        )
        return f"'{escaped}'"
