"""TAC -> C source generation with value-semantics-preserving wrappers.

MiniC guarantees that no two names alias.  Plain C breaks that guarantee the
moment an array is passed to a function, because the array decays to a pointer
and the callee can now mutate the caller's storage.  To keep MiniC semantics we
never let a bare array cross an assignment or a call boundary: every array and
every string type is emitted as a **one-field wrapper struct**

    typedef struct { int  data[3][3]; } arr_int_3_3;
    typedef struct { char data[6];     } str_6;

Structs already have value semantics in C (copy on assignment, pass/return by
value), so a MiniC ``struct`` maps straight to a C ``struct`` of the same name.

String literal assignments use a C99 compound literal:

    label = (str_6){ .data = "grid1" };
"""
import re
from typing import Dict, List, Optional, Tuple

from ..ir.tac import (
    Opcode, TACInstruction, TACFunction, TACProgram,
    Temp, Var, Constant, Label,
)

_TYPE_RE = re.compile(
    r"^(?P<base>struct\s+\w+|int|float|char|void)"
    r"(?:\[(?P<d1>\d+)\])?(?:\[(?P<d2>\d+)\])?$"
)


class ParsedType:
    __slots__ = ("base", "dims")

    def __init__(self, base: str, dims: Tuple[int, ...]):
        self.base = base                 # 'int' | 'float' | 'char' | 'void' | 'struct X'
        self.dims = dims                 # () | (n,) | (n, m)

    @property
    def is_array(self) -> bool:
        return len(self.dims) > 0

    @property
    def c_base(self) -> str:
        if self.base.startswith("struct "):
            return self.base.split()[1]
        return self.base


def parse_type(type_str: str) -> ParsedType:
    type_str = (type_str or "int").strip()
    m = _TYPE_RE.match(type_str)
    if not m:
        # Unknown / row-of-2D-array shapes -> fall back to int scalar.
        return ParsedType("int", ())
    base = m.group("base")
    if base.startswith("struct"):
        base = "struct " + base.split()[1]
    dims: List[int] = []
    if m.group("d1") is not None:
        dims.append(int(m.group("d1")))
    if m.group("d2") is not None:
        dims.append(int(m.group("d2")))
    return ParsedType(base, tuple(dims))


def wrapper_name(pt: ParsedType) -> str:
    if pt.c_base == "char" and len(pt.dims) == 1:
        return f"str_{pt.dims[0]}"
    return "arr_" + pt.c_base + "".join(f"_{d}" for d in pt.dims)


class CEmitter:
    def __init__(self, prog: TACProgram):
        self.prog = prog
        self.wrappers: Dict[str, ParsedType] = {}   # name -> ParsedType
        self._lines: List[str] = []

    # -- public ------------------------------------------------------------
    def emit(self) -> str:
        self._collect_wrappers()
        self._lines = []
        self._emit_prelude()
        self._emit_struct_typedefs()
        self._emit_wrapper_typedefs()
        self._emit_globals()
        self._emit_prototypes()
        for func in self.prog.functions:
            self._emit_function(func)
        return "\n".join(self._lines) + "\n"

    # -- type helpers ----------------------------------------------------- -
    def c_type(self, type_str: str) -> str:
        pt = parse_type(type_str)
        if pt.is_array:
            return wrapper_name(pt)
        return pt.c_base

    def _register(self, type_str: str) -> None:
        pt = parse_type(type_str)
        if pt.is_array:
            self.wrappers[wrapper_name(pt)] = pt

    def _collect_wrappers(self) -> None:
        for _n, t, _i in self.prog.global_vars:
            self._register(t)
        for func in self.prog.functions:
            self._register(func.return_type)
            for _pn, pt in func.params:
                self._register(pt)
            for t in func.local_types.values():
                self._register(t)

    # -- sections -------------------------------------------------------- -
    def _emit_prelude(self) -> None:
        self._lines += [
            "/* Generated by MiniC codegen (TAC -> C). Do not edit. */",
            "#include <stdio.h>",
            "#include <stdlib.h>",
            "#include <string.h>",
            "",
        ]

    def _emit_struct_typedefs(self) -> None:
        structs = self.prog.structs
        if not structs:
            return
        emitted: set = set()

        def emit_one(name: str) -> None:
            if name in emitted or name not in structs:
                return
            fields = structs[name]
            for ftype in fields.values():
                pt = parse_type(ftype)
                if pt.base.startswith("struct "):
                    emit_one(pt.c_base)
            emitted.add(name)
            self._lines.append(f"typedef struct {{")
            for fname, ftype in fields.items():
                pt = parse_type(ftype)
                dim = "".join(f"[{d}]" for d in pt.dims)
                self._lines.append(f"    {pt.c_base} {fname}{dim};")
            self._lines.append(f"}} {name};")
        for sname in structs:
            emit_one(sname)
        self._lines.append("")

    def _emit_wrapper_typedefs(self) -> None:
        if not self.wrappers:
            return
        for name in sorted(self.wrappers):
            pt = self.wrappers[name]
            dim = "".join(f"[{d}]" for d in pt.dims)
            self._lines.append(
                f"typedef struct {{ {pt.c_base} data{dim}; }} {name};")
        self._lines.append("")

    def _emit_globals(self) -> None:
        if not self.prog.global_vars:
            return
        for name, type_str, init in self.prog.global_vars:
            ct = self.c_type(type_str)
            if init is not None and not parse_type(type_str).is_array:
                self._lines.append(f"{ct} {name} = {self._const_literal(init, type_str)};")
            else:
                self._lines.append(f"{ct} {name};")
        self._lines.append("")

    def _signature(self, func: TACFunction) -> str:
        ret = self.c_type(func.return_type)
        if func.params:
            params = ", ".join(f"{self.c_type(pt)} {pn}" for pn, pt in func.params)
        else:
            params = "void"
        return f"{ret} {func.name}({params})"

    def _emit_prototypes(self) -> None:
        for func in self.prog.functions:
            self._lines.append(self._signature(func) + ";")
        self._lines.append("")

    def _emit_function(self, func: TACFunction) -> None:
        self._lines.append(self._signature(func) + " {")
        param_names = {pn for pn, _ in func.params}

        # hoist every local + temporary declaration to the top (C89-safe: no
        # jumping past an initializer, since alloc never carries one).
        for name, type_str in func.local_types.items():
            if name in param_names:
                continue
            self._lines.append(f"    {self.c_type(type_str)} {name};")
        if len(func.local_types) > len(param_names):
            self._lines.append("")

        params_stack: List[str] = []
        for inst in func.instructions:
            for line in self._emit_instruction(inst, func, params_stack):
                self._lines.append(line)
        self._lines.append("}")
        self._lines.append("")

    # -- instruction lowering ------------------------------------------- -
    def _emit_instruction(self, inst: TACInstruction, func: TACFunction,
                          params_stack: List[str]) -> List[str]:
        op = inst.opcode
        E = self._expr

        if op == Opcode.LABEL:
            return [f"{inst.dst}: ;"]
        if op == Opcode.COMMENT:
            return [f"    /* {inst.annotation} */"]
        if op == Opcode.ALLOC_LOCAL:
            return []
        if op == Opcode.JUMP:
            return [f"    goto {inst.dst};"]
        if op == Opcode.JUMP_IF_TRUE:
            return [f"    if ({E(inst.src1)}) goto {inst.dst};"]
        if op == Opcode.JUMP_IF_FALSE:
            return [f"    if (!({E(inst.src1)})) goto {inst.dst};"]

        if op == Opcode.ASSIGN:
            if isinstance(inst.src1, Constant) and inst.src1.type_str == "string":
                wname = self.c_type(self._operand_type(inst.dst, func))
                return [f'    {E(inst.dst)} = ({wname}){{ .data = '
                        f'{self._c_string(inst.src1.value)} }};']
            return [f"    {E(inst.dst)} = {E(inst.src1)};"]

        _BIN = {
            Opcode.ADD: "+", Opcode.SUB: "-", Opcode.MUL: "*", Opcode.DIV: "/",
            Opcode.MOD: "%", Opcode.EQ: "==", Opcode.NE: "!=", Opcode.LT: "<",
            Opcode.LE: "<=", Opcode.GT: ">", Opcode.GE: ">=",
            Opcode.LOGIC_AND: "&&", Opcode.LOGIC_OR: "||",
        }
        if op in _BIN:
            return [f"    {E(inst.dst)} = ({E(inst.src1)} {_BIN[op]} "
                    f"{E(inst.src2)});"]
        if op == Opcode.NEG:
            return [f"    {E(inst.dst)} = -({E(inst.src1)});"]
        if op == Opcode.LOGIC_NOT:
            return [f"    {E(inst.dst)} = !({E(inst.src1)});"]

        if op == Opcode.PARAM:
            params_stack.append(E(inst.src1))
            return []
        if op == Opcode.CALL:
            n = int(inst.src2) if inst.src2 is not None else 0
            args = params_stack[-n:] if n else []
            del params_stack[len(params_stack) - n:]
            call = f"{inst.src1}({', '.join(args)})"
            if inst.dst is not None:
                return [f"    {E(inst.dst)} = {call};"]
            return [f"    {call};"]
        if op == Opcode.RETURN:
            if inst.src1 is not None:
                return [f"    return {E(inst.src1)};"]
            return ["    return;"]

        if op == Opcode.LOAD_ARR_1D:
            return [f"    {E(inst.dst)} = {E(inst.src1)}.data[{E(inst.src2)}];"]
        if op == Opcode.LOAD_ARR_2D:
            return [f"    {E(inst.dst)} = {E(inst.src1)}.data[{E(inst.src2)}]"
                    f"[{E(inst.src3)}];"]
        if op == Opcode.STORE_ARR_1D:
            return [f"    {E(inst.dst)}.data[{E(inst.src1)}] = {E(inst.src2)};"]
        if op == Opcode.STORE_ARR_2D:
            return [f"    {E(inst.dst)}.data[{E(inst.src1)}][{E(inst.src2)}] "
                    f"= {E(inst.src3)};"]
        if op == Opcode.GET_FIELD:
            return [f"    {E(inst.dst)} = {E(inst.src1)}.{inst.src2};"]
        if op == Opcode.SET_FIELD:
            return [f"    {E(inst.dst)}.{inst.src1} = {E(inst.src2)};"]

        raise NotImplementedError(f"codegen: unhandled opcode {op}")

    # -- operands ------------------------------------------------------- -
    def _expr(self, operand: object) -> str:
        if isinstance(operand, Constant):
            return self._const_literal(operand.value, operand.type_str)
        if isinstance(operand, (Var, Temp)):
            return str(operand)
        if isinstance(operand, Label):
            return operand.name
        return str(operand)

    def _const_literal(self, value: object, type_str: str) -> str:
        if type_str == "string":
            return self._c_string(str(value))
        if type_str == "char":
            return self._c_char(str(value))
        if type_str == "float":
            return repr(float(value))
        return str(int(value))

    @staticmethod
    def _c_string(value: str) -> str:
        return '"' + CEmitter._escape(value) + '"'

    @staticmethod
    def _c_char(value: str) -> str:
        if value == "":
            return "'\\0'"
        return "'" + CEmitter._escape(value) + "'"

    @staticmethod
    def _escape(value: str) -> str:
        out = []
        for ch in value:
            if ch == "\\":
                out.append("\\\\")
            elif ch == '"':
                out.append('\\"')
            elif ch == "'":
                out.append("\\'")
            elif ch == "\n":
                out.append("\\n")
            elif ch == "\t":
                out.append("\\t")
            elif ch == "\r":
                out.append("\\r")
            elif ch == "\0":
                out.append("\\0")
            else:
                out.append(ch)
        return "".join(out)

    def _operand_type(self, operand: object, func: TACFunction) -> str:
        if isinstance(operand, (Var, Temp)):
            name = str(operand)
            if name in func.local_types:
                return func.local_types[name]
            for pn, pt in func.params:
                if pn == name:
                    return pt
            if isinstance(operand, (Var, Temp)) and operand.type_str:
                return operand.type_str
        return "int"


def emit_c(prog: TACProgram) -> str:
    return CEmitter(prog).emit()
